// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhxfunKueqBkRPkpS7g8E2orMPmTiUzqM',
    appId: '1:333749953108:web:92d5e29738390de17fc3c1',
    messagingSenderId: '333749953108',
    projectId: 'por2-34971',
    authDomain: 'por2-34971.firebaseapp.com',
    storageBucket: 'por2-34971.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCmgONW4xz_eKf77zTPwGwnopwpKuKHg',
    appId: '1:333749953108:android:6de5dca71619bb057fc3c1',
    messagingSenderId: '333749953108',
    projectId: 'por2-34971',
    storageBucket: 'por2-34971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv5EbgE1rywAHxESLlT3K0u8sLS1v6Pno',
    appId: '1:333749953108:ios:897662d0cf24c10f7fc3c1',
    messagingSenderId: '333749953108',
    projectId: 'por2-34971',
    storageBucket: 'por2-34971.appspot.com',
    iosBundleId: 'com.example.firebaseExapmle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv5EbgE1rywAHxESLlT3K0u8sLS1v6Pno',
    appId: '1:333749953108:ios:048f67e831fe8ae87fc3c1',
    messagingSenderId: '333749953108',
    projectId: 'por2-34971',
    storageBucket: 'por2-34971.appspot.com',
    iosBundleId: 'com.example.firebaseExapmle.RunnerTests',
  );
}
